# Generated by Django 5.0.6 on 2024-08-28 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetailModel",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "INACTIVE"),
                            (1, "ACTIVE"),
                            (2, "PENDING"),
                            (3, "DELETED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255, null=True)),
                ("profile_pic_url", models.URLField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "oauth_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("oauth_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "user_type",
                    models.IntegerField(
                        choices=[(0, "INDIVIDUAL"), (1, "CLIENT_ASSOCIATED")],
                        default=0,
                        help_text="Defines the type of user: 'Individual' or 'Client Associated'.",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="This field is for client-associated users only. Leave blank for individual users.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="client.clientdetailmodel",
                    ),
                ),
                (
                    "workspaces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="workspace.workspacedetailmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Detail",
                "verbose_name_plural": "User Details",
                "db_table": "user_detail",
            },
        ),
        migrations.CreateModel(
            name="UserWorkspaceMappingDetailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "INACTIVE"),
                            (1, "ACTIVE"),
                            (2, "PENDING"),
                            (3, "DELETED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userdetailmodel",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.workspacedetailmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace User Mapping Detail",
                "verbose_name_plural": "Workspace User Mapping Details",
                "db_table": "workspace_user_mapping_detail",
            },
        ),
    ]
