# Generated by Django 5.0.6 on 2024-08-28 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDetailModel",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "INACTIVE"),
                            (1, "ACTIVE"),
                            (2, "PENDING"),
                            (3, "DELETED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="client.clientdetailmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Detail",
                "verbose_name_plural": "Workspace Details",
                "db_table": "workspace_detail",
            },
        ),
    ]
