# Generated by Django 5.0.6 on 2024-08-28 16:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientDetailModel",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "INACTIVE"),
                            (1, "ACTIVE"),
                            (2, "PENDING"),
                            (3, "DELETED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Client Detail",
                "verbose_name_plural": "Client Details",
                "db_table": "client_detail",
            },
        ),
    ]
