"""
Generated by "django-admin startproject" using Django 5.0.

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv, find_dotenv
from common_utils import get_env_key

_ = load_dotenv(find_dotenv())  # read local .env file

POSTGRES_DB_NAME = get_env_key("POSTGRES_DB_NAME")
POSTGRES_DB_USER = get_env_key("POSTGRES_DB_USER")
POSTGRES_DB_PASSWORD = get_env_key("POSTGRES_DB_PASSWORD")
POSTGRES_DB_HOST = get_env_key("POSTGRES_DB_HOST")
POSTGRES_DB_PORT = get_env_key("POSTGRES_DB_PORT")


# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# temp:: BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Static files (CSS, JavaScript, Images)

# STATICFILES_DIRS :list of dirs where Django will search for additional static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/dist"),
    os.path.join(BASE_DIR, "static/admin"),
    os.path.join(BASE_DIR, "static/graphene_django"),
    os.path.join(BASE_DIR, "static"),
    # BASE_DIR / "dist",# add dist folder path generated by a frontend build process
]

# STATIC_URL: prefix that Django uses to generate the URLs for those static files in your HTML
STATIC_URL = "/static/"

# STATIC_ROOT directory where Django will collect all static files when you run the collectstatic command
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "<your django key created on project setup using djangoadmin start app command>"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "graphene_django",
    "corsheaders",
    "agent",
    "action",
    "client",
    "channels",
    "llm",
    "memory",
    "plan",
    "profile",
    "tool",
    "user",
    "workspace",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "main.jwt_authentication_middleware.JWTAuthenticationMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [
                os.path.join(BASE_DIR, "profile/templates"),  # path to templates folder
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "main.settings.jinja2.environment"  # path to options file
        }
    },

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),  # path to templates folder
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": POSTGRES_DB_NAME,
#         "USER": POSTGRES_DB_USER,
#         "PASSWORD": POSTGRES_DB_PASSWORD,
#         "HOST": POSTGRES_DB_HOST,
#         "PORT": POSTGRES_DB_PORT,
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'agent_bourne',
        'USER': 'agent_bourne_user',
        'PASSWORD': 'my_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# If you want to use Redis for session management, add the following settings
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

GRAPHENE = {
    "SCHEMA": "main.main_schema.schema"
}

# Web Server - uses wsgi.py
WSGI_APPLICATION = "main.wsgi.application"

# Asynchronous Server - uses asgi.py
ASGI_APPLICATION = 'main.asgi.application'
